//
//  AssetImage.swift
//  SuWB
//
//  Created by 王文臻 on 15/9/29.
//  Copyright © 2015年 王文臻. All rights reserved.
//

import Foundation
import UIKit

extension UIImage {
    enum Asset : String {
        case AvatarDefault = "avatar_default"
        case AvatarDefaultBig = "avatar_default_big"
        case AvatarDefaultSmall = "avatar_default_small"
        case AvatarEnterpriseVip = "avatar_enterprise_vip"
        case AvatarEnterpriseVipOs7 = "avatar_enterprise_vip_os7"
        case AvatarGrassroot = "avatar_grassroot"
        case AvatarGrassrootOs7 = "avatar_grassroot_os7"
        case AvatarVgirl = "avatar_vgirl"
        case AvatarVgirlOs7 = "avatar_vgirl_os7"
        case AvatarVip = "avatar_vip"
        case AvatarVipOs7 = "avatar_vip_os7"
        case Close = "Close"
        case ComposeCamerabuttonBackground = "compose_camerabutton_background"
        case ComposeCamerabuttonBackgroundHighlighted = "compose_camerabutton_background_highlighted"
        case ComposeCamerabuttonBackgroundHighlightedOs7 = "compose_camerabutton_background_highlighted_os7"
        case ComposeCamerabuttonBackgroundOs7 = "compose_camerabutton_background_os7"
        case ComposeEmoticonbuttonBackground = "compose_emoticonbutton_background"
        case ComposeEmoticonbuttonBackgroundHighlighted = "compose_emoticonbutton_background_highlighted"
        case ComposeEmoticonbuttonBackgroundHighlightedOs7 = "compose_emoticonbutton_background_highlighted_os7"
        case ComposeEmoticonbuttonBackgroundOs7 = "compose_emoticonbutton_background_os7"
        case ComposeMentionbuttonBackground = "compose_mentionbutton_background"
        case ComposeMentionbuttonBackgroundHighlighted = "compose_mentionbutton_background_highlighted"
        case ComposeMentionbuttonBackgroundHighlightedOs7 = "compose_mentionbutton_background_highlighted_os7"
        case ComposeMentionbuttonBackgroundOs7 = "compose_mentionbutton_background_os7"
        case ComposePicAdd = "compose_pic_add"
        case ComposePicAddHighlighted = "compose_pic_add_highlighted"
        case ComposePicAddHighlightedOs7 = "compose_pic_add_highlighted_os7"
        case ComposePicAddOs7 = "compose_pic_add_os7"
        case ComposeToolbarBackground = "compose_toolbar_background"
        case ComposeToolbarBackgroundOs7 = "compose_toolbar_background_os7"
        case ComposeToolbarPicture = "compose_toolbar_picture"
        case ComposeToolbarPictureHighlighted = "compose_toolbar_picture_highlighted"
        case ComposeToolbarPictureHighlightedOs7 = "compose_toolbar_picture_highlighted_os7"
        case ComposeToolbarPictureOs7 = "compose_toolbar_picture_os7"
        case ComposeTrendbuttonBackground = "compose_trendbutton_background"
        case ComposeTrendbuttonBackgroundHighlighted = "compose_trendbutton_background_highlighted"
        case ComposeTrendbuttonBackgroundHighlightedOs7 = "compose_trendbutton_background_highlighted_os7"
        case ComposeTrendbuttonBackgroundOs7 = "compose_trendbutton_background_os7"
        case App = "app"
        case Cast = "cast"
        case Expand = "expand"
        case FindPeople = "find_people"
        case GameCenter = "game_center"
        case HotStatus = "hot_status"
        case More = "more"
        case Movie = "movie"
        case Music = "music"
        case Near = "near"
        case SearchbarTextfieldBackground = "searchbar_textfield_background"
        case SearchbarTextfieldBackgroundOs7 = "searchbar_textfield_background_os7"
        case SearchbarTextfieldSearchIcon = "searchbar_textfield_search_icon"
        case SquareAd = "square_ad"
        case Video = "video"
        case TimelineCardBottomBackground = "timeline_card_bottom_background"
        case TimelineCardBottomBackgroundHighlighted = "timeline_card_bottom_background_highlighted"
        case TimelineCardBottomBackgroundHighlightedOs7 = "timeline_card_bottom_background_highlighted_os7"
        case TimelineCardBottomBackgroundOs7 = "timeline_card_bottom_background_os7"
        case TimelineCardBottomLine = "timeline_card_bottom_line"
        case TimelineCardBottomLineHighlighted = "timeline_card_bottom_line_highlighted"
        case TimelineCardBottomLineHighlightedOs7 = "timeline_card_bottom_line_highlighted_os7"
        case TimelineCardBottomLineOs7 = "timeline_card_bottom_line_os7"
        case TimelineCardLeftbottomHighlighted = "timeline_card_leftbottom_highlighted"
        case TimelineCardLeftbottomHighlightedOs7 = "timeline_card_leftbottom_highlighted_os7"
        case TimelineCardMiddlebottomHighlighted = "timeline_card_middlebottom_highlighted"
        case TimelineCardMiddlebottomHighlightedOs7 = "timeline_card_middlebottom_highlighted_os7"
        case TimelineCardRightbottomHighlighted = "timeline_card_rightbottom_highlighted"
        case TimelineCardRightbottomHighlightedOs7 = "timeline_card_rightbottom_highlighted_os7"
        case TimelineCardTopBackground = "timeline_card_top_background"
        case TimelineCardTopBackgroundHighlighted = "timeline_card_top_background_highlighted"
        case TimelineCardTopBackgroundHighlightedOs7 = "timeline_card_top_background_highlighted_os7"
        case TimelineCardTopBackgroundOs7 = "timeline_card_top_background_os7"
        case TimelineIconComment = "timeline_icon_comment"
        case TimelineIconCommentOs7 = "timeline_icon_comment_os7"
        case TimelineIconMore = "timeline_icon_more"
        case TimelineIconMoreHighlighted = "timeline_icon_more_highlighted"
        case TimelineIconMoreHighlightedOs7 = "timeline_icon_more_highlighted_os7"
        case TimelineIconMoreOs7 = "timeline_icon_more_os7"
        case TimelineIconRetweet = "timeline_icon_retweet"
        case TimelineIconRetweetOs7 = "timeline_icon_retweet_os7"
        case TimelineIconUnlike = "timeline_icon_unlike"
        case TimelineIconUnlikeOs7 = "timeline_icon_unlike_os7"
        case TimelineImageGif = "timeline_image_gif"
        case TimelineImagePlaceholder = "timeline_image_placeholder"
        case TimelineNewStatusBackground = "timeline_new_status_background"
        case TimelineNewStatusBackgroundOs7 = "timeline_new_status_background_os7"
        case TimelineRetweetBackground = "timeline_retweet_background"
        case TimelineRetweetBackgroundOs7 = "timeline_retweet_background_os7"
        case CommonIconMembership = "common_icon_membership"
        case CommonIconMembershipExpired = "common_icon_membership_expired"
        case CommonIconMembershipLevel1 = "common_icon_membership_level1"
        case CommonIconMembershipLevel2 = "common_icon_membership_level2"
        case CommonIconMembershipLevel3 = "common_icon_membership_level3"
        case CommonIconMembershipLevel4 = "common_icon_membership_level4"
        case CommonIconMembershipLevel5 = "common_icon_membership_level5"
        case CommonIconMembershipLevel6 = "common_icon_membership_level6"
        case NavigationbarArrowDown = "navigationbar_arrow_down"
        case NavigationbarArrowDownOs7 = "navigationbar_arrow_down_os7"
        case NavigationbarArrowUp = "navigationbar_arrow_up"
        case NavigationbarArrowUpOs7 = "navigationbar_arrow_up_os7"
        case NavigationbarBack = "navigationbar_back"
        case NavigationbarBackHighlighted = "navigationbar_back_highlighted"
        case NavigationbarBackHighlightedOs7 = "navigationbar_back_highlighted_os7"
        case NavigationbarBackOs7 = "navigationbar_back_os7"
        case NavigationbarBackground = "navigationbar_background"
        case NavigationbarButtonBackground = "navigationbar_button_background"
        case NavigationbarButtonBackgroundDisable = "navigationbar_button_background_disable"
        case NavigationbarButtonBackgroundPushed = "navigationbar_button_background_pushed"
        case NavigationbarButtonSendBackground = "navigationbar_button_send_background"
        case NavigationbarButtonSendBackgroundDisabled = "navigationbar_button_send_background_disabled"
        case NavigationbarButtonSendBackgroundPushed = "navigationbar_button_send_background_pushed"
        case NavigationbarFilterBackgroundHighlighted = "navigationbar_filter_background_highlighted"
        case NavigationbarFilterBackgroundHighlightedOs7 = "navigationbar_filter_background_highlighted_os7"
        case NavigationbarFriendsearch = "navigationbar_friendsearch"
        case NavigationbarFriendsearchHighlighted = "navigationbar_friendsearch_highlighted"
        case NavigationbarFriendsearchHighlightedOs7 = "navigationbar_friendsearch_highlighted_os7"
        case NavigationbarFriendsearchOs7 = "navigationbar_friendsearch_os7"
        case NavigationbarMore = "navigationbar_more"
        case NavigationbarMoreHighlighted = "navigationbar_more_highlighted"
        case NavigationbarMoreHighlightedOs7 = "navigationbar_more_highlighted_os7"
        case NavigationbarMoreOs7 = "navigationbar_more_os7"
        case NavigationbarPop = "navigationbar_pop"
        case NavigationbarPopHighlighted = "navigationbar_pop_highlighted"
        case NavigationbarPopHighlightedOs7 = "navigationbar_pop_highlighted_os7"
        case NavigationbarPopOs7 = "navigationbar_pop_os7"
        case NewDot = "new_dot"
        case NewDotOs7 = "new_dot_os7"
        case NewFeature1 = "new_feature_1"
        case NewFeature2 = "new_feature_2"
        case NewFeature3 = "new_feature_3"
        case NewFeatureBackground = "new_feature_background"
        case NewFeatureButton = "new_feature_button"
        case NewFeatureButtonHighlighted = "new_feature_button_highlighted"
        case NewFeatureButtonHighlightedPad = "new_feature_button_highlighted_pad"
        case NewFeatureButtonPad = "new_feature_button_pad"
        case NewFeatureFinishButton = "new_feature_finish_button"
        case NewFeatureFinishButtonHighlighted = "new_feature_finish_button_highlighted"
        case NewFeaturePagecontrolCheckedPoint = "new_feature_pagecontrol_checked_point"
        case NewFeaturePagecontrolPoint = "new_feature_pagecontrol_point"
        case NewFeatureShareFalse = "new_feature_share_false"
        case NewFeatureShareTrue = "new_feature_share_true"
        case CommonCardBackground = "common_card_background"
        case CommonCardBackgroundHighlighted = "common_card_background_highlighted"
        case CommonCardBackgroundHighlightedOs7 = "common_card_background_highlighted_os7"
        case CommonCardBackgroundOs7 = "common_card_background_os7"
        case CommonCardBottomBackground = "common_card_bottom_background"
        case CommonCardBottomBackgroundHighlighted = "common_card_bottom_background_highlighted"
        case CommonCardBottomBackgroundHighlightedOs7 = "common_card_bottom_background_highlighted_os7"
        case CommonCardBottomBackgroundOs7 = "common_card_bottom_background_os7"
        case CommonCardMiddleBackground = "common_card_middle_background"
        case CommonCardMiddleBackgroundHighlighted = "common_card_middle_background_highlighted"
        case CommonCardMiddleBackgroundHighlightedOs7 = "common_card_middle_background_highlighted_os7"
        case CommonCardMiddleBackgroundOs7 = "common_card_middle_background_os7"
        case CommonCardTopBackground = "common_card_top_background"
        case CommonCardTopBackgroundHighlighted = "common_card_top_background_highlighted"
        case CommonCardTopBackgroundHighlightedOs7 = "common_card_top_background_highlighted_os7"
        case CommonCardTopBackgroundOs7 = "common_card_top_background_os7"
        case CommonIconArrow = "common_icon_arrow"
        case CommonIconCheckmark = "common_icon_checkmark"
        case MainBadge = "main_badge"
        case MainBadgeOs7 = "main_badge_os7"
        case TabbarBackground = "tabbar_background"
        case TabbarComposeButton = "tabbar_compose_button"
        case TabbarComposeButtonHighlighted = "tabbar_compose_button_highlighted"
        case TabbarComposeButtonHighlightedOs7 = "tabbar_compose_button_highlighted_os7"
        case TabbarComposeButtonOs7 = "tabbar_compose_button_os7"
        case TabbarComposeIconAdd = "tabbar_compose_icon_add"
        case TabbarComposeIconAddHighlighted = "tabbar_compose_icon_add_highlighted"
        case TabbarComposeIconAddHighlightedOs7 = "tabbar_compose_icon_add_highlighted_os7"
        case TabbarComposeIconAddOs7 = "tabbar_compose_icon_add_os7"
        case TabbarDiscover = "tabbar_discover"
        case TabbarDiscoverOs7 = "tabbar_discover_os7"
        case TabbarDiscoverSelected = "tabbar_discover_selected"
        case TabbarDiscoverSelectedOs7 = "tabbar_discover_selected_os7"
        case TabbarHome = "tabbar_home"
        case TabbarHomeOs7 = "tabbar_home_os7"
        case TabbarHomeSelected = "tabbar_home_selected"
        case TabbarHomeSelectedOs7 = "tabbar_home_selected_os7"
        case TabbarMessageCenter = "tabbar_message_center"
        case TabbarMessageCenterOs7 = "tabbar_message_center_os7"
        case TabbarMessageCenterSelected = "tabbar_message_center_selected"
        case TabbarMessageCenterSelectedOs7 = "tabbar_message_center_selected_os7"
        case TabbarProfile = "tabbar_profile"
        case TabbarProfileOs7 = "tabbar_profile_os7"
        case TabbarProfileSelected = "tabbar_profile_selected"
        case TabbarProfileSelectedOs7 = "tabbar_profile_selected_os7"
        case TabbarSlider = "tabbar_slider"
        
        var image: UIImage {
            return UIImage(asset: self)
        }
    }
    
    convenience init(asset: Asset) {
        self.init(named: asset.rawValue)!
    }
}

